// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: Pulsador2

#ifndef _PULSADOR2_UI_H
#define _PULSADOR2_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Nivel;
extern lv_obj_t * ui_Nivelmarca;
extern lv_obj_t * ui_Brujula;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Buzamiento;
extern lv_obj_t * ui_Buzamiento1;
extern lv_obj_t * ui_Buzamiento2;
extern lv_obj_t * ui_Norte;
extern lv_obj_t * ui_Norte1;
extern lv_obj_t * ui_Sur;
extern lv_obj_t * ui_Oeste;
extern lv_obj_t * ui_Este;
void ui_event_De1a2(lv_event_t * e);
extern lv_obj_t * ui_De1a2;
void ui_event_De1a3(lv_event_t * e);
extern lv_obj_t * ui_De1a3;
void ui_event_Medir(lv_event_t * e);
extern lv_obj_t * ui_Medir;
extern lv_obj_t * ui_Bateria;
extern lv_obj_t * ui_Bateria1;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Latitud;
extern lv_obj_t * ui_Longitud;
extern lv_obj_t * ui_Altura;
extern lv_obj_t * ui_Fecha;
extern lv_obj_t * ui_Hora;
void ui_event_De2a3(lv_event_t * e);
extern lv_obj_t * ui_De2a3;
void ui_event_De2a1(lv_event_t * e);
extern lv_obj_t * ui_De2a1;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_Label23;
extern lv_obj_t * ui_Label24;
extern lv_obj_t * ui_Bateria2;
extern lv_obj_t * ui_Bateria3;
// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
extern lv_obj_t * ui_Screen3;
void ui_event_Wifi(lv_event_t * e);
extern lv_obj_t * ui_Wifi;
extern lv_obj_t * ui_Wifi1;
extern lv_obj_t * ui_Wifi2;
void ui_event_Calibrar(lv_event_t * e);
extern lv_obj_t * ui_Calibrar;
extern lv_obj_t * ui_Calibrar1;
void ui_event_Borrar_medidas(lv_event_t * e);
extern lv_obj_t * ui_Borrar_medidas;
extern lv_obj_t * ui_Borrar_medidas1;
void ui_event_De3a1(lv_event_t * e);
extern lv_obj_t * ui_De3a1;
void ui_event_De3a2(lv_event_t * e);
extern lv_obj_t * ui_De3a2;
extern lv_obj_t * ui_Bateria4;
extern lv_obj_t * ui_Bateria5;
// SCREEN: ui_Screen4
void ui_Screen4_screen_init(void);
extern lv_obj_t * ui_Screen4;
extern lv_obj_t * ui_Magneto1;
extern lv_obj_t * ui_Inclinometro1;
extern lv_obj_t * ui_Latitud1;
extern lv_obj_t * ui_Longitud1;
extern lv_obj_t * ui_Altura1;
extern lv_obj_t * ui_Fecha1;
extern lv_obj_t * ui_Hora1;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Desea_guardar;
void ui_event_NOPO(lv_event_t * e);
extern lv_obj_t * ui_NOPO;
extern lv_obj_t * ui_NOPO1;
void ui_event_SIPI(lv_event_t * e);
extern lv_obj_t * ui_SIPI;
extern lv_obj_t * ui_SIPI1;
// SCREEN: ui_Screen5
void ui_Screen5_screen_init(void);
extern lv_obj_t * ui_Screen5;
extern lv_obj_t * ui_Wifi3;
extern lv_obj_t * ui_Wifi4;
extern lv_obj_t * ui_Wifi5;
extern lv_obj_t * ui_Calibrar2;
extern lv_obj_t * ui_Calibrar3;
extern lv_obj_t * ui_Borrar_medidas2;
extern lv_obj_t * ui_Borrar_medidas3;
extern lv_obj_t * ui_Calibrando;
extern lv_obj_t * ui_Calibrando1;
extern lv_obj_t * ui_Calibrando2;
void ui_event_Salir1(lv_event_t * e);
extern lv_obj_t * ui_Salir1;
// SCREEN: ui_Screen6
void ui_Screen6_screen_init(void);
extern lv_obj_t * ui_Screen6;
extern lv_obj_t * ui_Wifi6;
extern lv_obj_t * ui_Wifi7;
extern lv_obj_t * ui_Wifi8;
extern lv_obj_t * ui_Calibrar4;
extern lv_obj_t * ui_Calibrar5;
extern lv_obj_t * ui_Borrar_medidas4;
extern lv_obj_t * ui_Borrar_medidas5;
extern lv_obj_t * ui_Borrando;
extern lv_obj_t * ui_Borrando1;
extern lv_obj_t * ui_Borrando2;
void ui_event_Salir2(lv_event_t * e);
extern lv_obj_t * ui_Salir2;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_pngwing2_com_png);    // assets/pngwing2.com.png
LV_IMG_DECLARE(ui_img_1871344563);    // assets/pngwing.com (4).png






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
