// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: Pulsador2

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C"
{
#endif

    void MIDIERON(lv_event_t *e);
    void WIFION(lv_event_t *e);
    void CALIBRARON(lv_event_t *e);
    void BORRARON(lv_event_t *e);
    void NOPOFUNCION(lv_event_t *e);
    void SIPIFUNCION(lv_event_t *e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
