idf_component_register(SRCS ui_Screen1.c
                            ui_Screen2.c
                            ui_Screen3.c
                            ui_Screen4.c
                            ui_Screen5.c
                            ui_Screen6.c
                            ui.c
                            ui_comp_hook.c
                            ui_helpers.c
                            ui_events.c
                            ui_img_pngwing2_com_png.c
                            ui_img_1871344563.c
                    INCLUDE_DIRS "include"
                    REQUIRES lvgl)
