// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: Pulsador2

#include "ui.h"

void WIFION(lv_event_t * e)
{
	// Your code here
}
