// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: Pulsador2

#include "ui.h"

void ui_Screen7_screen_init(void)
{
    ui_Screen7 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Wifi9 = lv_obj_create(ui_Screen7);
    lv_obj_set_width(ui_Wifi9, 150);
    lv_obj_set_height(ui_Wifi9, 50);
    lv_obj_set_x(ui_Wifi9, lv_pct(0));
    lv_obj_set_y(ui_Wifi9, lv_pct(-25));
    lv_obj_set_align(ui_Wifi9, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Wifi9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Wifi10 = lv_label_create(ui_Wifi9);
    lv_obj_set_width(ui_Wifi10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Wifi10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_y(ui_Wifi10, 0);
    lv_obj_set_x(ui_Wifi10, lv_pct(20));
    lv_obj_set_align(ui_Wifi10, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Wifi10, "Wifi");

    ui_Wifi11 = lv_label_create(ui_Wifi9);
    lv_obj_set_width(ui_Wifi11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Wifi11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_y(ui_Wifi11, 0);
    lv_obj_set_x(ui_Wifi11, lv_pct(-20));
    lv_obj_set_align(ui_Wifi11, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_Wifi11, "ON");

    ui_Borrar_medidas6 = lv_obj_create(ui_Screen7);
    lv_obj_set_width(ui_Borrar_medidas6, 150);
    lv_obj_set_height(ui_Borrar_medidas6, 50);
    lv_obj_set_x(ui_Borrar_medidas6, 0);
    lv_obj_set_y(ui_Borrar_medidas6, lv_pct(25));
    lv_obj_set_align(ui_Borrar_medidas6, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Borrar_medidas6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Borrar_medidas7 = lv_label_create(ui_Borrar_medidas6);
    lv_obj_set_width(ui_Borrar_medidas7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Borrar_medidas7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Borrar_medidas7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Borrar_medidas7, "Borrar medidas");

    ui_Reseteando = lv_obj_create(ui_Screen7);
    lv_obj_set_width(ui_Reseteando, 192);
    lv_obj_set_height(ui_Reseteando, 160);
    lv_obj_set_align(ui_Reseteando, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Reseteando, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Reseteando, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Reseteando, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Reseteando, lv_color_hex(0x7B7878), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Reseteando, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Reseteando, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Reseteando1 = lv_label_create(ui_Reseteando);
    lv_obj_set_width(ui_Reseteando1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Reseteando1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Reseteando1, lv_pct(0));
    lv_obj_set_y(ui_Reseteando1, lv_pct(-20));
    lv_obj_set_align(ui_Reseteando1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Reseteando1, "Reseteando ...");

    ui_Reseteando2 = lv_spinner_create(ui_Reseteando, 1000, 90);
    lv_obj_set_width(ui_Reseteando2, lv_pct(30));
    lv_obj_set_height(ui_Reseteando2, lv_pct(30));
    lv_obj_set_x(ui_Reseteando2, 0);
    lv_obj_set_y(ui_Reseteando2, lv_pct(15));
    lv_obj_set_align(ui_Reseteando2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Reseteando2, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_arc_width(ui_Reseteando2, 7, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_Reseteando2, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Reseteando2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Reseteando2, 7, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Salir3 = lv_obj_create(ui_Reseteando);
    lv_obj_set_height(ui_Salir3, 25);
    lv_obj_set_width(ui_Salir3, lv_pct(100));
    lv_obj_set_x(ui_Salir3, lv_pct(0));
    lv_obj_set_y(ui_Salir3, lv_pct(45));
    lv_obj_set_align(ui_Salir3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Salir3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Salir3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Salir3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Salir3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Salir3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Salir3, ui_event_Salir3, LV_EVENT_ALL, NULL);

}
