// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: Pulsador2

#include "ui.h"

void ui_Screen4_screen_init(void)
{
    ui_Screen4 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Magneto1 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Magneto1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Magneto1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Magneto1, lv_pct(-60));
    lv_obj_set_y(ui_Magneto1, lv_pct(-40));
    lv_obj_set_align(ui_Magneto1, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_Magneto1, "Brujula:");
    lv_obj_set_style_text_font(ui_Magneto1, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Inclinometro1 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Inclinometro1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Inclinometro1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Inclinometro1, lv_pct(-60));
    lv_obj_set_y(ui_Inclinometro1, lv_pct(-30));
    lv_obj_set_align(ui_Inclinometro1, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_Inclinometro1, "Buzamien:");
    lv_obj_set_style_text_font(ui_Inclinometro1, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Latitud1 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Latitud1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Latitud1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Latitud1, lv_pct(-60));
    lv_obj_set_y(ui_Latitud1, lv_pct(-20));
    lv_obj_set_align(ui_Latitud1, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_Latitud1, "Latitud:");
    lv_obj_set_style_text_font(ui_Latitud1, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Longitud1 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Longitud1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Longitud1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Longitud1, lv_pct(-60));
    lv_obj_set_y(ui_Longitud1, lv_pct(-10));
    lv_obj_set_align(ui_Longitud1, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_Longitud1, "Longitud:");
    lv_obj_set_style_text_font(ui_Longitud1, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Altura1 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Altura1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Altura1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_y(ui_Altura1, 0);
    lv_obj_set_x(ui_Altura1, lv_pct(-60));
    lv_obj_set_align(ui_Altura1, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_Altura1, "Altura:");
    lv_obj_set_style_text_font(ui_Altura1, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Fecha1 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Fecha1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Fecha1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Fecha1, lv_pct(-60));
    lv_obj_set_y(ui_Fecha1, lv_pct(10));
    lv_obj_set_align(ui_Fecha1, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_Fecha1, "Fecha:");
    lv_obj_set_style_text_font(ui_Fecha1, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Hora1 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Hora1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Hora1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Hora1, lv_pct(-60));
    lv_obj_set_y(ui_Hora1, lv_pct(20));
    lv_obj_set_align(ui_Hora1, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_Hora1, "Hora:");
    lv_obj_set_style_text_font(ui_Hora1, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, lv_pct(15));
    lv_obj_set_y(ui_Label1, lv_pct(-40));
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "0°");

    ui_Label2 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, lv_pct(15));
    lv_obj_set_y(ui_Label2, lv_pct(-30));
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "-90°");

    ui_Label3 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, lv_pct(15));
    lv_obj_set_y(ui_Label3, lv_pct(-20));
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "data1");

    ui_Label4 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, lv_pct(15));
    lv_obj_set_y(ui_Label4, lv_pct(-10));
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "data2");

    ui_Label5 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, lv_pct(15));
    lv_obj_set_y(ui_Label5, lv_pct(0));
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "data3");

    ui_Label6 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, lv_pct(15));
    lv_obj_set_y(ui_Label6, lv_pct(10));
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "data4");

    ui_Label7 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, lv_pct(15));
    lv_obj_set_y(ui_Label7, lv_pct(20));
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "data5");

    ui_Desea_guardar = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Desea_guardar, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Desea_guardar, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Desea_guardar, lv_pct(-19));
    lv_obj_set_y(ui_Desea_guardar, lv_pct(36));
    lv_obj_set_align(ui_Desea_guardar, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Desea_guardar, "Desea guardar?");

    ui_NOPO = lv_obj_create(ui_Screen4);
    lv_obj_set_width(ui_NOPO, 70);
    lv_obj_set_height(ui_NOPO, 30);
    lv_obj_set_x(ui_NOPO, 65);
    lv_obj_set_y(ui_NOPO, 98);
    lv_obj_set_align(ui_NOPO, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_NOPO, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_shadow_color(ui_NOPO, lv_color_hex(0x7B7878), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_opa(ui_NOPO, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_width(ui_NOPO, 2, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_spread(ui_NOPO, 3, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_color(ui_NOPO, lv_color_hex(0x7B7878), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_opa(ui_NOPO, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_width(ui_NOPO, 2, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_spread(ui_NOPO, 3, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_NOPO1 = lv_label_create(ui_NOPO);
    lv_obj_set_width(ui_NOPO1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NOPO1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_NOPO1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_NOPO1, "NO");

    ui_SIPI = lv_obj_create(ui_Screen4);
    lv_obj_set_width(ui_SIPI, 70);
    lv_obj_set_height(ui_SIPI, 30);
    lv_obj_set_x(ui_SIPI, 65);
    lv_obj_set_y(ui_SIPI, 135);
    lv_obj_set_align(ui_SIPI, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SIPI, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_shadow_color(ui_SIPI, lv_color_hex(0x7B7878), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_opa(ui_SIPI, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_width(ui_SIPI, 2, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_spread(ui_SIPI, 3, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_color(ui_SIPI, lv_color_hex(0x7B7878), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_opa(ui_SIPI, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_width(ui_SIPI, 2, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_spread(ui_SIPI, 3, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_SIPI1 = lv_label_create(ui_SIPI);
    lv_obj_set_width(ui_SIPI1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SIPI1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SIPI1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SIPI1, "SI");

    lv_obj_add_event_cb(ui_NOPO, ui_event_NOPO, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SIPI, ui_event_SIPI, LV_EVENT_ALL, NULL);

}
