// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: Pulsador2

#include "ui.h"

void ui_Screen5_screen_init(void)
{
    ui_Screen5 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Wifi3 = lv_obj_create(ui_Screen5);
    lv_obj_set_width(ui_Wifi3, 150);
    lv_obj_set_height(ui_Wifi3, 50);
    lv_obj_set_x(ui_Wifi3, lv_pct(0));
    lv_obj_set_y(ui_Wifi3, lv_pct(-25));
    lv_obj_set_align(ui_Wifi3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Wifi3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Wifi4 = lv_label_create(ui_Wifi3);
    lv_obj_set_width(ui_Wifi4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Wifi4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_y(ui_Wifi4, 0);
    lv_obj_set_x(ui_Wifi4, lv_pct(20));
    lv_obj_set_align(ui_Wifi4, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Wifi4, "Wifi");

    ui_Wifi5 = lv_label_create(ui_Wifi3);
    lv_obj_set_width(ui_Wifi5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Wifi5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_y(ui_Wifi5, 0);
    lv_obj_set_x(ui_Wifi5, lv_pct(-20));
    lv_obj_set_align(ui_Wifi5, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_Wifi5, "ON");

    ui_Calibrar2 = lv_obj_create(ui_Screen5);
    lv_obj_set_width(ui_Calibrar2, 150);
    lv_obj_set_height(ui_Calibrar2, 50);
    lv_obj_set_align(ui_Calibrar2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Calibrar2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Calibrar3 = lv_label_create(ui_Calibrar2);
    lv_obj_set_width(ui_Calibrar3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Calibrar3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Calibrar3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Calibrar3, "Calibrar");

    ui_Borrar_medidas2 = lv_obj_create(ui_Screen5);
    lv_obj_set_width(ui_Borrar_medidas2, 150);
    lv_obj_set_height(ui_Borrar_medidas2, 50);
    lv_obj_set_x(ui_Borrar_medidas2, 0);
    lv_obj_set_y(ui_Borrar_medidas2, lv_pct(25));
    lv_obj_set_align(ui_Borrar_medidas2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Borrar_medidas2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Borrar_medidas3 = lv_label_create(ui_Borrar_medidas2);
    lv_obj_set_width(ui_Borrar_medidas3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Borrar_medidas3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Borrar_medidas3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Borrar_medidas3, "Borrar medidas");

    ui_Calibrando = lv_obj_create(ui_Screen5);
    lv_obj_set_width(ui_Calibrando, 192);
    lv_obj_set_height(ui_Calibrando, 160);
    lv_obj_set_align(ui_Calibrando, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Calibrando, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Calibrando, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Calibrando, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Calibrando, lv_color_hex(0x7B7878), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Calibrando, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Calibrando, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Calibrando1 = lv_label_create(ui_Calibrando);
    lv_obj_set_width(ui_Calibrando1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Calibrando1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Calibrando1, lv_pct(0));
    lv_obj_set_y(ui_Calibrando1, lv_pct(-20));
    lv_obj_set_align(ui_Calibrando1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Calibrando1, "Calibrando ...");

    ui_Calibrando2 = lv_spinner_create(ui_Calibrando, 1000, 90);
    lv_obj_set_width(ui_Calibrando2, lv_pct(30));
    lv_obj_set_height(ui_Calibrando2, lv_pct(30));
    lv_obj_set_x(ui_Calibrando2, 0);
    lv_obj_set_y(ui_Calibrando2, lv_pct(15));
    lv_obj_set_align(ui_Calibrando2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Calibrando2, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_arc_width(ui_Calibrando2, 7, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_Calibrando2, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Calibrando2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Calibrando2, 7, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Salir1 = lv_obj_create(ui_Calibrando);
    lv_obj_set_height(ui_Salir1, 25);
    lv_obj_set_width(ui_Salir1, lv_pct(100));
    lv_obj_set_x(ui_Salir1, lv_pct(0));
    lv_obj_set_y(ui_Salir1, lv_pct(45));
    lv_obj_set_align(ui_Salir1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Salir1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Salir1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Salir1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Salir1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Salir1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Salir1, ui_event_Salir1, LV_EVENT_ALL, NULL);

}
