// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: Pulsador2

#include "ui.h"

void ui_Screen6_screen_init(void)
{
    ui_Screen6 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Wifi6 = lv_obj_create(ui_Screen6);
    lv_obj_set_width(ui_Wifi6, 150);
    lv_obj_set_height(ui_Wifi6, 50);
    lv_obj_set_x(ui_Wifi6, lv_pct(0));
    lv_obj_set_y(ui_Wifi6, lv_pct(-25));
    lv_obj_set_align(ui_Wifi6, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Wifi6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Wifi7 = lv_label_create(ui_Wifi6);
    lv_obj_set_width(ui_Wifi7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Wifi7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_y(ui_Wifi7, 0);
    lv_obj_set_x(ui_Wifi7, lv_pct(20));
    lv_obj_set_align(ui_Wifi7, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Wifi7, "Wifi");

    ui_Wifi8 = lv_label_create(ui_Wifi6);
    lv_obj_set_width(ui_Wifi8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Wifi8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_y(ui_Wifi8, 0);
    lv_obj_set_x(ui_Wifi8, lv_pct(-20));
    lv_obj_set_align(ui_Wifi8, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_Wifi8, "ON");

    ui_Borrar_medidas4 = lv_obj_create(ui_Screen6);
    lv_obj_set_width(ui_Borrar_medidas4, 150);
    lv_obj_set_height(ui_Borrar_medidas4, 50);
    lv_obj_set_x(ui_Borrar_medidas4, 0);
    lv_obj_set_y(ui_Borrar_medidas4, lv_pct(25));
    lv_obj_set_align(ui_Borrar_medidas4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Borrar_medidas4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Borrar_medidas5 = lv_label_create(ui_Borrar_medidas4);
    lv_obj_set_width(ui_Borrar_medidas5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Borrar_medidas5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Borrar_medidas5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Borrar_medidas5, "Borrar medidas");

    ui_Borrando = lv_obj_create(ui_Screen6);
    lv_obj_set_width(ui_Borrando, 192);
    lv_obj_set_height(ui_Borrando, 160);
    lv_obj_set_align(ui_Borrando, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Borrando, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Borrando, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Borrando, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Borrando, lv_color_hex(0x7B7878), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Borrando, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Borrando, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Borrando1 = lv_label_create(ui_Borrando);
    lv_obj_set_width(ui_Borrando1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Borrando1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Borrando1, lv_pct(0));
    lv_obj_set_y(ui_Borrando1, lv_pct(-20));
    lv_obj_set_align(ui_Borrando1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Borrando1, "Borrando medidas ...");

    ui_Borrando2 = lv_spinner_create(ui_Borrando, 1000, 90);
    lv_obj_set_width(ui_Borrando2, lv_pct(30));
    lv_obj_set_height(ui_Borrando2, lv_pct(30));
    lv_obj_set_x(ui_Borrando2, 0);
    lv_obj_set_y(ui_Borrando2, lv_pct(15));
    lv_obj_set_align(ui_Borrando2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Borrando2, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_arc_width(ui_Borrando2, 7, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_Borrando2, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Borrando2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Borrando2, 7, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Salir2 = lv_obj_create(ui_Borrando);
    lv_obj_set_height(ui_Salir2, 25);
    lv_obj_set_width(ui_Salir2, lv_pct(100));
    lv_obj_set_x(ui_Salir2, lv_pct(0));
    lv_obj_set_y(ui_Salir2, lv_pct(45));
    lv_obj_set_align(ui_Salir2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Salir2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Salir2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Salir2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Salir2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Salir2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Salir2, ui_event_Salir2, LV_EVENT_ALL, NULL);

}
