// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: Pulsador2

#include "ui.h"

void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Wifi = lv_obj_create(ui_Screen3);
    lv_obj_set_width(ui_Wifi, 150);
    lv_obj_set_height(ui_Wifi, 50);
    lv_obj_set_x(ui_Wifi, lv_pct(0));
    lv_obj_set_y(ui_Wifi, lv_pct(-25));
    lv_obj_set_align(ui_Wifi, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Wifi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Wifi, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Wifi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Wifi, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Wifi, lv_color_hex(0x30BE54), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_opa(ui_Wifi, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_width(ui_Wifi, 2, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_spread(ui_Wifi, 3, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_color(ui_Wifi, lv_color_hex(0xEBE8E8), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_opa(ui_Wifi, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_width(ui_Wifi, 2, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_spread(ui_Wifi, 3, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Wifi1 = lv_label_create(ui_Wifi);
    lv_obj_set_width(ui_Wifi1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Wifi1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_y(ui_Wifi1, 0);
    lv_obj_set_x(ui_Wifi1, lv_pct(20));
    lv_obj_set_align(ui_Wifi1, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Wifi1, "Wifi");

    ui_Wifi2 = lv_label_create(ui_Wifi);
    lv_obj_set_width(ui_Wifi2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Wifi2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_y(ui_Wifi2, 0);
    lv_obj_set_x(ui_Wifi2, lv_pct(-20));
    lv_obj_set_align(ui_Wifi2, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_Wifi2, "ON");

    ui_Calibrar = lv_obj_create(ui_Screen3);
    lv_obj_set_width(ui_Calibrar, 150);
    lv_obj_set_height(ui_Calibrar, 50);
    lv_obj_set_align(ui_Calibrar, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Calibrar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_shadow_color(ui_Calibrar, lv_color_hex(0x7B7878), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_opa(ui_Calibrar, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_width(ui_Calibrar, 2, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_spread(ui_Calibrar, 3, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_color(ui_Calibrar, lv_color_hex(0xEBE8E8), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_opa(ui_Calibrar, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_width(ui_Calibrar, 2, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_spread(ui_Calibrar, 3, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Calibrar1 = lv_label_create(ui_Calibrar);
    lv_obj_set_width(ui_Calibrar1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Calibrar1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Calibrar1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Calibrar1, "Calibrar");

    ui_Borrar_medidas = lv_obj_create(ui_Screen3);
    lv_obj_set_width(ui_Borrar_medidas, 150);
    lv_obj_set_height(ui_Borrar_medidas, 50);
    lv_obj_set_x(ui_Borrar_medidas, 0);
    lv_obj_set_y(ui_Borrar_medidas, lv_pct(25));
    lv_obj_set_align(ui_Borrar_medidas, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Borrar_medidas, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_shadow_color(ui_Borrar_medidas, lv_color_hex(0x7B7878), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_opa(ui_Borrar_medidas, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_width(ui_Borrar_medidas, 2, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_spread(ui_Borrar_medidas, 3, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_color(ui_Borrar_medidas, lv_color_hex(0xE4E2E2), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_opa(ui_Borrar_medidas, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_width(ui_Borrar_medidas, 2, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_spread(ui_Borrar_medidas, 3, LV_PART_MAIN | LV_STATE_FOCUSED);

    lv_obj_set_style_shadow_color(ui_Borrar_medidas, lv_color_hex(0xEBE8E8), LV_PART_SCROLLBAR | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_opa(ui_Borrar_medidas, 255, LV_PART_SCROLLBAR | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_width(ui_Borrar_medidas, 2, LV_PART_SCROLLBAR | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_spread(ui_Borrar_medidas, 3, LV_PART_SCROLLBAR | LV_STATE_FOCUSED);

    ui_Borrar_medidas1 = lv_label_create(ui_Borrar_medidas);
    lv_obj_set_width(ui_Borrar_medidas1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Borrar_medidas1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Borrar_medidas1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Borrar_medidas1, "Borrar medidas");

    ui_De3a1 = lv_obj_create(ui_Screen3);
    lv_obj_set_width(ui_De3a1, lv_pct(10));
    lv_obj_set_height(ui_De3a1, lv_pct(70));
    lv_obj_set_x(ui_De3a1, lv_pct(45));
    lv_obj_set_y(ui_De3a1, lv_pct(-5));
    lv_obj_set_align(ui_De3a1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_De3a1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_De3a1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_De3a1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_De3a1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_De3a1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_De3a2 = lv_obj_create(ui_Screen3);
    lv_obj_set_width(ui_De3a2, lv_pct(10));
    lv_obj_set_height(ui_De3a2, lv_pct(70));
    lv_obj_set_x(ui_De3a2, lv_pct(-45));
    lv_obj_set_y(ui_De3a2, lv_pct(-5));
    lv_obj_set_align(ui_De3a2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_De3a2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_De3a2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_De3a2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_De3a2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_De3a2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Bateria4 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_Bateria4, &ui_img_1871344563);
    lv_obj_set_width(ui_Bateria4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Bateria4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Bateria4, 95);
    lv_obj_set_y(ui_Bateria4, -145);
    lv_obj_set_align(ui_Bateria4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Bateria4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Bateria4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Bateria4, 15);
    lv_obj_set_style_radius(ui_Bateria4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor(ui_Bateria4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_Bateria4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Bateria5 = lv_slider_create(ui_Bateria4);
    lv_slider_set_value(ui_Bateria5, 50, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Bateria5) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Bateria5, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bateria5, 30);
    lv_obj_set_height(ui_Bateria5, 11);
    lv_obj_set_align(ui_Bateria5, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Bateria5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bateria5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Bateria5, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Bateria5, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bateria5, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Bateria5, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bateria5, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Wifi, ui_event_Wifi, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Calibrar, ui_event_Calibrar, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Borrar_medidas, ui_event_Borrar_medidas, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_De3a1, ui_event_De3a1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_De3a2, ui_event_De3a2, LV_EVENT_ALL, NULL);

}
