// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: Pulsador2

#include "ui.h"

void ui_Screen5_screen_init(void)
{
    ui_Screen5 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Calibrando = lv_obj_create(ui_Screen5);
    lv_obj_set_width(ui_Calibrando, 192);
    lv_obj_set_height(ui_Calibrando, 160);
    lv_obj_set_align(ui_Calibrando, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Calibrando, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Calibrando, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Calibrando, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Calibrando, lv_color_hex(0x7B7878), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Calibrando, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Calibrando, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Calibrando1 = lv_label_create(ui_Calibrando);
    lv_obj_set_width(ui_Calibrando1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Calibrando1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Calibrando1, lv_pct(0));
    lv_obj_set_y(ui_Calibrando1, lv_pct(-20));
    lv_obj_set_align(ui_Calibrando1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Calibrando1, "Calibrando ...");

    ui_Calibrando2 = lv_spinner_create(ui_Calibrando, 1000, 90);
    lv_obj_set_width(ui_Calibrando2, lv_pct(30));
    lv_obj_set_height(ui_Calibrando2, lv_pct(30));
    lv_obj_set_x(ui_Calibrando2, 0);
    lv_obj_set_y(ui_Calibrando2, lv_pct(15));
    lv_obj_set_align(ui_Calibrando2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Calibrando2, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_arc_width(ui_Calibrando2, 7, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_Calibrando2, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Calibrando2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Calibrando2, 7, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Salir1 = lv_obj_create(ui_Calibrando);
    lv_obj_set_height(ui_Salir1, 25);
    lv_obj_set_width(ui_Salir1, lv_pct(100));
    lv_obj_set_x(ui_Salir1, lv_pct(0));
    lv_obj_set_y(ui_Salir1, lv_pct(45));
    lv_obj_set_align(ui_Salir1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Salir1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Salir1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Salir1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Salir1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Salir1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Salir1, ui_event_Salir1, LV_EVENT_ALL, NULL);

}
